################################################################################
# > ⚠️ AI-Generated Module / Generated by Bob, an AI assistant powered by IBM watsonx
################################################################################

terraform {
  required_version = ">= 1.5.7"

  cloud {
    organization = "jose-merchan"
    workspaces {
      name = "eks-vault-vcs"
    }
  }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 6.0"
    }
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = "~> 2.35"
    }
    helm = {
      source  = "hashicorp/helm"
      version = "~> 3.0" # latest: 3.2.0
    }
    acme = {
      source  = "vancluever/acme"
      version = "~> 2.0" # latest: 2.48.2
    }
    tfe = {
      source  = "hashicorp/tfe"
      version = "~> 0.78" # latest: 0.78.0
    }
    tls = {
      source  = "hashicorp/tls"
      version = "~> 4.0"
    }
  }
}
